services:
  - type: web
    name: werd
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: WEALTHX_STRIPE_MONTHLY_PRICE_ID
        sync: false
      - key: WEALTHX_STRIPE_YEARLY_PRICE_ID
        sync: false
      - key: WEALTHX_PUBLIC_BASE_URL
        sync: false
