name: Build compact EOD from IEX HIST (T+1)

on:
  schedule:
    - cron: "0 9 * * *"      # 09:00 UTC（夏令 ~05:00 ET / 冬令 ~04:00 ET）
    - cron: "30 12 * * *"    # 12:30 UTC（夏令 ~08:30 ET / 冬令 ~07:30 ET）
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install iex_parser requests

      - name: Parse HIST (T+1, compact, shards)
        id: parse
        continue-on-error: true
        run: |
          python scripts/parse_hist_all.py
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Commit changes (only when updated)
        if: steps.parse.outputs.exit_code != '78'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/latest.json docs/eod-*.json docs/shards/*.json 2>/dev/null || true
          if ! git diff --cached --quiet; then
            git commit -m "Update compact EOD latest.json"
            git push
          else
            echo "No changes to commit."
          fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - uses: actions/deploy-pages@v4
